### PR TITLE
Test against rails 5

### PR DESCRIPTION
**Pull request by lazyatom**
This removes `alias_method_chain`, which is deprecated in Rails 5. 

It also removes tests against Rails 3.x; in order to test against Rails 5, we have to use a version of Ruby that is not compatible with Rails 3.x. Technically we could fix this by using a more sophisticated build matrix, but Rails 3 is sufficiently old now that we might consider just dropping support.

### CODE REVIEW

**Review by andydust — APPROVED** [review]
Sounds good.

**Comment by lazyatom** [comment]
Can you either push this to rubygems, or add me as an owner -- whenever you get the chance? :)

**Comment by andydust** [comment]
Made you an owner.

**Comment by andreaskaempf** [comment]
Hi Andy, hope things are well with you. You seem to have included me on this thread by accident. I have just moved to Germany, working with www.thinkbiganalytics.com, loving it here.  Please say hi to Efe and the others.  All best, Andreas

**Comment by andydust** [comment]
@andreaskaempf glad to hear everything's going well. You were included on this thread because you are 'watching' the repository. If you click 'Unwatch' at the top of this page you will no longer receive notifications. All the best, Andy.

**Pull request merged**
